# Generated by Django 3.1.6 on 2021-02-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Giris', '0002_sayfa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seyahat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adi', models.CharField(max_length=100, verbose_name='Seyahat ettiğin yer')),
                ('bolge', models.CharField(max_length=100, verbose_name='Seyahat ettiğin bölge')),
                ('tarih', models.DateTimeField(verbose_name='Gittiğin Tarih')),
                ('ani', models.TextField(blank=True, verbose_name='Anıların')),
            ],
        ),
    ]
