# Generated by Django 3.1.6 on 2021-02-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Giris', '0004_quote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gezi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adi', models.CharField(max_length=25, verbose_name='Adınız Soyadınız')),
                ('yer', models.CharField(max_length=100, verbose_name='Seyahat ettiğin yer')),
                ('bolge', models.CharField(max_length=100, verbose_name='Seyahat ettiğin bölge')),
                ('foto', models.FileField(blank=True, upload_to='uploads/')),
                ('ani', models.TextField(blank=True, verbose_name='Anıların')),
            ],
        ),
        migrations.DeleteModel(
            name='Seyahat',
        ),
    ]
